# /etc/systemd/system/gvmd.service.d/socket-perms.conf
# Ensures gvmd socket is accessible by Docker containers after every restart
#
# Install:
#   sudo mkdir -p /etc/systemd/system/gvmd.service.d/
#   sudo cp socket-perms.conf /etc/systemd/system/gvmd.service.d/
#   sudo systemctl daemon-reload
#   sudo systemctl restart gvmd
[Service]
ExecStartPost=/bin/sleep 2
ExecStartPost=/bin/chmod 660 /run/gvmd/gvmd.sock
